//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LABORATORIO_1_PROGRA2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotasEstudiantes
    {
        public int id { get; set; }
        public Nullable<decimal> lab1 { get; set; }
        public Nullable<decimal> lab2 { get; set; }
        public Nullable<decimal> lab3 { get; set; }
        public Nullable<decimal> parcial1 { get; set; }
        public Nullable<decimal> parcial2 { get; set; }
        public Nullable<decimal> parcial3 { get; set; }
        public Nullable<decimal> nota { get; set; }
        public string nombre { get; set; }
    }
}
