//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrodeNotas
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<int> lab1 { get; set; }
        public Nullable<int> lab2 { get; set; }
        public Nullable<int> lab3 { get; set; }
        public Nullable<int> parcial1 { get; set; }
        public Nullable<int> parcial2 { get; set; }
        public Nullable<int> parcial3 { get; set; }
    }
}
